FROM alpine:latest
MAINTAINER GoCD <go-cd-dev@googlegroups.com>

ARG GO_WORKING_DIR="/go-working-dir"
ARG VOLUME_DIR="/godata"

ARG GOCD_VERSION="<%= gocd_version %>"
ARG DOWNLOAD_URL="<%= download_url %>"

ADD ${DOWNLOAD_URL} /tmp/go-server.zip

RUN apk add --update-cache openjdk8-jre-base git mercurial subversion tini openssh-client bash && \
# unzip the zip file into /go-server, after stripping the first path prefix
  unzip /tmp/go-server.zip -d / && \
  mv go-server-${GOCD_VERSION} /go-server && \
# Exposing volumes in a simple manner, and setup links behind-the-scenes
# to match GoCD's directory structure
  mkdir -p ${GO_WORKING_DIR} && \
<% %w(artifacts config db logs plugins addons).each do |dir| -%>
  mkdir -p ${VOLUME_DIR}/<%= dir %> && \
  ln -sf ${VOLUME_DIR}/<%= dir %> ${GO_WORKING_DIR}/<%= dir %> && \
<% end -%>
  adduser -D go && \
  chown -R go:go ${VOLUME_DIR} ${GO_WORKING_DIR}

# allow mounting ssh keys, dotfiles, and the go server config and data
VOLUME ["/home/go", "${VOLUME_DIR}"]

# the ports that go server runs on
EXPOSE 8153 8154

USER go
ENTRYPOINT ["/sbin/tini", "--"]
WORKDIR ${GO_WORKING_DIR}
ENV GO_CONFIG_DIR=${GO_WORKING_DIR}/config
ENV SERVER_WORK_DIR=${GO_WORKING_DIR}
ENV STDOUT_LOG_FILE=${GO_WORKING_DIR}/logs/go-server.out.log
CMD ["/go-server/server.sh"]
