# Copyright 2024 Thoughtworks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

###############################################################################################
# This file is autogenerated by the repository at https://github.com/gocd/gocd.
# Please file any issues or PRs at https://github.com/gocd/gocd
###############################################################################################

FROM curlimages/curl:latest AS gocd-server-unzip
USER root
ARG TARGETARCH
ARG UID=1000
RUN curl --fail --location --silent --show-error "https://download.gocd.org/binaries/24.2.0-19076/generic/go-server-24.2.0-19076.zip" > /tmp/go-server-24.2.0-19076.zip && \
    unzip -q /tmp/go-server-24.2.0-19076.zip -d / && \
    mkdir -p /go-server/wrapper /go-server/bin && \
    mv -v /go-server-24.2.0/LICENSE /go-server/LICENSE && \
    mv -v /go-server-24.2.0/bin/go-server /go-server/bin/go-server && \
    mv -v /go-server-24.2.0/lib /go-server/lib && \
    mv -v /go-server-24.2.0/logs /go-server/logs && \
    mv -v /go-server-24.2.0/run /go-server/run && \
    mv -v /go-server-24.2.0/wrapper-config /go-server/wrapper-config && \
    WRAPPERARCH=$(if [ $TARGETARCH == amd64 ]; then echo x86-64; elif [ $TARGETARCH == arm64 ]; then echo arm-64; else echo $TARGETARCH is unknown!; exit 1; fi) && \
    mv -v /go-server-24.2.0/wrapper/wrapper-linux-$WRAPPERARCH* /go-server/wrapper/ && \
    mv -v /go-server-24.2.0/wrapper/libwrapper-linux-$WRAPPERARCH* /go-server/wrapper/ && \
    mv -v /go-server-24.2.0/wrapper/wrapper.jar /go-server/wrapper/ && \
    chown -R ${UID}:0 /go-server && chmod -R g=u /go-server

FROM cgr.dev/chainguard/wolfi-base
ARG TARGETARCH

LABEL gocd.version="24.2.0" \
  description="GoCD server based on cgr.dev/chainguard/wolfi-base" \
  maintainer="GoCD Team <go-cd-dev@googlegroups.com>" \
  url="https://www.gocd.org" \
  gocd.full.version="24.2.0-19076" \
  gocd.git.sha="1406870fc6e121194028e55c4facc0c638d70007"

# the ports that GoCD server runs on
EXPOSE 8153

ADD https://github.com/krallin/tini/releases/download/v0.19.0/tini-static-${TARGETARCH} /usr/local/sbin/tini

# force encoding
ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8
ENV GO_JAVA_HOME="/gocd-jre"

ARG UID=1000

RUN \
# add mode and permissions for files we added above
  chmod 0755 /usr/local/sbin/tini && \
  chown root:root /usr/local/sbin/tini && \
# add our user and group first to make sure their IDs get assigned consistently, regardless of whatever dependencies get added
  adduser -D -u ${UID} -s /bin/bash -G root go && \
  apk add --no-cache git openssh-client bash curl procps glibc-locale-en && \
  curl --fail --location --silent --show-error "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.3%2B9/OpenJDK21U-jre_$(uname -m | sed -e s/86_//g)_linux_hotspot_21.0.3_9.tar.gz" --output /tmp/jre.tar.gz && \
  mkdir -p /gocd-jre && \
  tar -xf /tmp/jre.tar.gz -C /gocd-jre --strip 1 && \
  rm -rf /tmp/jre.tar.gz && \
  mkdir -p /go-server /docker-entrypoint.d /go-working-dir /godata

ADD docker-entrypoint.sh /

COPY --from=gocd-server-unzip /go-server /go-server
# ensure that logs are printed to console output
COPY --chown=go:root logback-include.xml /go-server/config/logback-include.xml
COPY --chown=go:root install-gocd-plugins git-clone-config /usr/local/sbin/

RUN chown -R go:root /docker-entrypoint.d /go-working-dir /godata /docker-entrypoint.sh && \
    chmod -R g=u /docker-entrypoint.d /go-working-dir /godata /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

USER go
