#!/usr/bin/env bash

yell() { echo "$0: $*" >&2; }
die() { yell "$*"; exit 111; }
try() { echo "$ $@" 1>&2; "$@" || die "cannot $*"; }

if [ ! -z "$CONFIG_GIT_REPO" ]; then 
  BRANCH=$([ ! -z $CONFIG_GIT_BRANCH ] && echo $CONFIG_GIT_BRANCH || echo "master" )
  try cd /godata/config
  try git init
  try git remote add origin $CONFIG_GIT_REPO 
  try git reset origin $BRANCH
  chown -R go:go /godata/config
fi
