#!/usr/bin/env bash

yell() { echo "$0: $*" >&2; }
die() { yell "$*"; exit 111; }
try() { echo "$ $@" 1>&2; "$@" || die "cannot $*"; }

if [ ! -z "$CONFIG_GIT_REPO" ]; then 
  BRANCH=${CONFIG_GIT_BRANCH}
  if [ -z "$BRANCH" ]; then 
    BRANCH="master"
  fi
  try rm -rf /godata/config
  try git clone -b $BRANCH $CONFIG_GIT_REPO /godata/config
  chown -R go:go /godata/config
fi
