#!/usr/bin/env bash

yell() { echo "$0: $*" >&2; }
die() { yell "$*"; exit 111; }
try() { echo "$ $@" 1>&2; "$@" || die "cannot $*"; }

if [ ! -z "$CONFIG_GIT_REPO" ]; then 
  BRANCH=${CONFIG_GIT_BRANCH:master}
  try rm -rf /go-working-dir/config
  try git clone -b $CONFIG_GIT_BRANCH $CONFIG_GIT_REPO /go-working-dir/config
fi
